### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghostss2016** [killerbigpoint/cs2-anticheat#12]
at TBAntiCheat.Detections.BaseCaller.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\BaseCaller.cs:line 104
2024-08-13 22:52:12.979 +10:00 [INFO] plugin:TB Anti-Cheat [TBAC] Exception in Aimbot -> Index was outside the bounds of the array. |    at TBAntiCheat.Detections.Modules.Aimbot.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\Modules\Aimbot.cs:line 398
   at TBAntiCheat.Detections.BaseCaller.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\BaseCaller.cs:line 104
2024-08-13 22:52:12.994 +10:00 [INFO] plugin:TB Anti-Cheat [TBAC] Exception in Aimbot -> Index was outside the bounds of the array. |    at TBAntiCheat.Detections.Modules.Aimbot.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\Modules\Aimbot.cs:line 398
   at TBAntiCheat.Detections.BaseCaller.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\BaseCaller.cs:line 104
2024-08-13 22:52:13.009 +10:00 [INFO] plugin:TB Anti-Cheat [TBAC] Exception in Aimbot -> Index was outside the bounds of the array. |    at TBAntiCheat.Detections.Modules.Aimbot.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\Modules\Aimbot.cs:line 398
   at TBAntiCheat.Detections.BaseCaller.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\BaseCaller.cs:line 104
2024-08-13 22:52:13.025 +10:00 [INFO] plugin:TB Anti-Cheat [TBAC] Exception in Aimbot -> Index was outside the bounds of the array. |    at TBAntiCheat.Detections.Modules.Aimbot.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\Modules\Aimbot.cs:line 398

**Comment by killerbigpoint** [comment]
Thank you for the report. How many were connected as the error happened and how long was the server running for?

**Comment by ghostss2016** [comment]
по русски можно, я с России

**Comment by ghostss2016** [comment]
2 часа карта на сервере, 22+ игроков

**Comment by ghostss2016** [comment]
at TBAntiCheat.Detections.BaseCaller.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\BaseCaller.cs:line 104
2024-08-22 12:21:02.275 +03:00 [INFO] plugin:TB Anti-Cheat [TBAC] Exception in Aimbot -> Index was outside the bounds of the array. |    at TBAntiCheat.Detections.Modules.Aimbot.OnPlayerTick(PlayerData player) in C:\Users\olive\Source\Repos\killerbigpoint\cs2-anticheat\Detections\Modules\Aimbot.cs:line 398

**Comment by freakexeuLow** [comment]
Hey and same problem...server restart is every 24 hours.....I have no idea when exactly it happens, I just had a check the logs and i saw it

CSSharp Version: 279
Metamod Version: 2.0.0-dev+1314

https://pastebin.com/7Y8SeU8P

**Comment by killerbigpoint** [comment]
Should be fixed in the next release
