### ISSUE TITLE
Support for SimpleAdmin

### ISSUE THREAD

**Issue by asapverneri** [killerbigpoint/cs2-anticheat#4]
Hello,

I was wondering if you could also add support for SimpleAdmin in the future?

**Comment by killerbigpoint** [comment]
Yeah sure. You got a link for it?

**Comment by mrahr** [comment]
> Yeah sure. You got a link for it?

https://github.com/daffyyyy/CS2-SimpleAdmin/

**Comment by asapverneri** [comment]
Also i got this error when i tried to run it in my windows server. Not sure if it remains on linux.

`2024-07-03 04:06:06.445 +03:00 [EROR] (cssharp:PluginManager) Failed to load plugin from C:\devservu\servu\game\csgo\addons\counterstrikesharp\plugins\TBAntiCheat\TBAntiCheat.dll
CounterStrikeSharp.API.Core.NativeException: Global Variables not initialized yet.
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.GetMaxClients() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 333
   at CounterStrikeSharp.API.Server.get_MaxPlayers() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Server.cs:line 140
   at TBAntiCheat.Core.Globals.Initialize(Boolean hotReload) in C:\Users\Oliver\source\repos\killerbigpoint\cs2-anticheat\Core\Globals.cs:line 37
   at TBAntiCheat.Core.ACCore.Load(Boolean hotReload) in C:\Users\Oliver\source\repos\killerbigpoint\cs2-anticheat\Core\ACCore.cs:line 30
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
`

**Comment by killerbigpoint** [comment]
I'll investigate that issue tomorrow. Thanks for telling me

**Comment by gha241** [comment]
Will this ever be implemented in the plugin or probably not?

**Comment by killerbigpoint** [comment]
> Will this ever be implemented in the plugin or probably not?

It will yes, when it's ready. I have no ETA for it right now though as I am working on other things
